name: Build & Deploy
on:
  push:
    branches: [dev]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME}}
          
          script:
            mkdir test_dev_project
            cd test_dev_project
            git clone -b ${{variables.TEST}} git@github.com:ecoleduweb/ProjetApplicationTODO2024.git
            echo 'Deployment successful to DEV server'
