name: Push Event Workflow

on: push

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: "Create env file"
        run: |
          touch .env
          echo DATABASE_TEST_URL=${{ secrets.DATABASE_TEST_URL }} >> .env
          echo DATABASE_DEV_URL=${{ secrets.DATABASE_DEV_URL }} >> .env
          cat .env

      - name: Run tests
        run: python -m pytest
